red/urls.py
from django.contrib import admin
from django.urls import path, include
import velvet.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',velvet.views.layout, name="layout"),
    path('velvet/home/', velvet.views.home, name='home'),
    path('velvet/new/', velvet.views.new, name='new'),
    path('velvet/new/', velvet.views.create, name='create'),
    path('velvet/newblog/', velvet.views.blogform, name='newblog'),
    path('velvet/<int:pk>/edit/', velvet.views.edit, name='edit'),
    path('velvet/<int:pk>/remove/', velvet.views.remove, name='remove'),
    #comment
    path('velvet/<int:blog_id>/comment_new/', velvet.views.detail, name='comment_new'),
    path('velvet/<int:comment_id>/comment_edit/', velvet.views.comment_edit, name='comment_edit'),
    path('velvet/<int:comment_id>/comment_delete/', velvet.views.comment_delete, name='comment_delete'),
    #hashtag
    path('velvet/hashtag/', velvet.views.hashtagform, name='hashtag'),
    path('velvet/<int:hashtag_id>/search/', velvet.views.search, name='search'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

velvet/urls.py
from django.urls import path

from .views import *
urlpatterns = [
    path('', MainpageView.as_view(), name='mainpage')
]

velvet/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()
    image = models.ImageField(upload_to='images/' ,blank=True)
    hashtags = models.ManyToManyField('Hashtag', blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    article_id = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="comments")
    comment_text = models.CharField(max_length=50)

    def __str__(self):
       return self.comment_text

class Hashtag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name       


# Create your models here.

velvet/forms.py
from django import forms
from .models import Blog, Comment, Hashtag

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'body', 'hashtags', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text"]

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ["name"]

velvet/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from .forms import BlogForm, CommentForm, HashtagForm
from .models import Blog, Comment, Hashtag
from django.views.generic. base import TemplateView
# Create your views here.

class MainpageView(TemplateView):
        template_name = 'layout.html'

def layout(request):
    return render(request, 'layout.html')

def home(request):
    blogs = Blog.objects
    hashtags = Hashtag.objects
    return render(request, 'home.html', {'blogs': blogs, 'hashtags': hashtags})

def new(request):
    return render(request, 'new.html')

def create(request):
    blog = Blog()
    blog.title = request.GET['title']
    blog.body = request.GET['body']
    blog.pub_date = timezone.datetime.now()
    blog.save()
    return redirect('/velvet/home/')

def blogform(request, blog=None):
    if request.method =='POST':
        form = BlogForm(request.POST, request.FILES, instance=blog)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.pub_date=timezone.now()
            blog.save()
            form.save_m2m()
            return redirect('home')
    else:
        form = BlogForm(instance=blog)
        return render(request, 'new.html', {'form':form})

def edit(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    return blogform(request, blog)


def remove(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    blog.delete()
    return redirect('home')

def comment_new(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article_id = blog
            comment.comment_text = form.cleaned_data["comment_text"]
            comment.save()
            return redirect("home")
    else:
        form = CommentForm()
        return render(request, "detail.html", {"form": form})

def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect("home")


def comment_edit(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment_text = form.cleaned_data["comment_text"]
            comment.save()
            return redirect("home")
    else:
        form = CommentForm(instance=comment)
        return render(request, "detail.html", {"form": form})

def hashtagform(request, hashtag=None):
    if request.method == 'POST':
        form = HashtagForm(request.POST, instance=hashtag)
        if form.is_valid():
            hashtag = form.save(commit=False)
            if Hashtag.objects.filter(name=form.cleaned_data['name']):
                form = HashtagForm()
                error_message = "이미 존재하는 해시태그 입니다."
                return render(request,'hashtag.html', {"form": form, "error_message": error_message})
            else:
                hashtag.name = form.cleaned_data['name']
                hashtag.save()
                return redirect('home')
    else:
        form = HashtagForm(instance=hashtag)
        return render(request, 'hashtag.html', {'form': form})  

def search(request, hashtag_id):
        hashtag = get_object_or_404(Hashtag, pk=hashtag_id)
        return render(request, 'search.html', {'hashtag': hashtag})

def detail(request, blog_id, commit=None):
        blog = get_object_or_404(Blog, id=blog_id)
        if request.method == 'POST':
                form = CommentForm(request.POST, instance=comment)
                if form.is_valid():
                        comment = form.save(commit=False)
                        comment.blog = blog
                        comment.comment_text = form.cleaned_data["comment_text"]
                        comment.save()
                        return redirect("home")

        else:
                form = CommentForm(instance=comment)
                return render(request, "detail.html", {'blog': blog, 'form': form})

velvet/templates/detail.html
{% extends 'layout.html' %}

{% block content %}
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <input class="btn btn-primary" type="submit" value="댓글 쓰기">
        </form>
    </div>
{% endblock %}

velvet/templates/edit.html
{% extends 'layout.html' %}

{% block content %}

    <form method="POST" >{% csrf_token %}
        {{ form.as_table}}
        <button type="submit" class="btn-default">Save</button>
    </form>
{% endblock %}    

velvet/templates/hashtag.html
{% extends 'layout.html' %}

{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('/static/app/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>New Hashtag</h1>
            <span class="subheading">해시태그를 추가하는 페이지 입니다.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto">
        {{ error_message }}
        <form method="POST">
          <div style="text-align:center; margin-right: 50px;">
            {% csrf_token %}
            {{form.as_table}}
          </div>
            <table>
            </table>
            <input class="btn btn-dark" style="text-align:center;"  type="submit" value="제출하기">
        </form>
    </div>
</div>
{% endblock %}

velvet/templates/home.html
{% extends 'layout.html' %}


{% block contnent1 %}
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Hashtag 검색
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      {% for hashtag in hashtags.all %}
      <a class="dropdown-item" href="{% url 'search' hashtag.id %}">{{ hashtag.name }}</a>
      {% endfor %}
    </div>
  </div>

{% for blog in blogs.all %}
    <hr style="border-color:lightcoral;">
    <h1 style="text-align: center; margin-top: 20px;">[ {{ blog.title }} ]</h1>
    <hr style="border: 1px; border-color: maroon;">
    <div class="container2" style="text-align: center;">
    	<p>{{ blog.pub_date }}</p>
        <p style="font-size: 35px;">{{ blog.body }}</p>
        <div>
        {% if blog.image %}
         <img class="card-img-top" src="{{ blog.image.url }}" alt="Card image cap">
        {% endif %}  
        </div>
        <div>
        {% for hashtag in blog.hashtags.all %}
         <p>{{ hashtag.name }}</p>
        {% endfor %}
        </div>
        <br>
    </div>
    <div style="text-align: center">
    	<a role="button" class="btn btn-primary" href="{% url 'edit' pk=blog.pk %}#portfolio1">수정</a>
    	<a role="button" class="btn btn-primary" href="{% url 'remove' pk=blog.pk %}#contact">삭제</a>
    </div>
    {% for comment in blog.comments.all %}
           <div class="alert alert-primary" style="margin: 10px; 0px;">
               <div class="container">
                   <h1 style="font-size: 15px;" class="display-4">{{ comment.comment_text }}</h1>
                   <div style="text-align: right;">
                       <a class="btn btn-secondary" href="{% url 'comment_edit' comment.id %}" role="button">수정</a> 
                       <a class="btn btn-danger" href="{% url 'comment_delete' comment.id %}" role="button">삭제</a>
                   </div>
                   
               </div>
           </div>
    {% endfor %}
    <div style="text-align: right;">
        <a class="btn btn-secondary" href="{% url 'comment_new' blog.id %}" role="button">댓글쓰기</a>
    </div>
    
{% endfor %}    
{% endblock %}

velvet/templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Creative - Start Bootstrap Theme</title>

  <!-- Font Awesome Icons -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'css/creative.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">성공회대 2019년 농촌 봉사 활동 페이지</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#">홈 </a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#services">농활의 장점</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'newblog' %}#portfolio1">게시판 쓰기</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'home' %}#contact">게시판</a>
          </li>
          <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'hashtag' %}#contact">해시태그 검색</a>
            </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">
          <h1 class="text-uppercase text-white font-weight-bold">힘들지만 재미있는 성공회대 농촌 봉사 활동!!</h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <p class="text-white-75 font-weight-light mb-5"># 영동 #괴목리 #폭염주의보 #핫태핫태 #너무 덥다 </p>
          <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">농활 의미</a>
        </div>
      </div>
    </div>
  </header>

  <!-- About Section -->
  <section class="page-section bg-primary" id="about">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="text-white mt-0">농활 의미</h2>
          <hr class="divider light my-4">
          <p class="text-white-50 mb-4">농촌 봉사 활동을 통해 우리나라 농민들의 마음과 고생을 직접 몸으로 느껴본다.</p>
          <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">봉사 활동</a>
        </div>
      </div>
    </div>
  </section>

  <!-- Services Section -->
  <section class="page-section" id="services">
    <div class="container" style="text-align: center;">
      <h2 class="text-center mt-0">농활의 장점</h2>
      <hr class="divider my-4">
      <div class="row">
        <div class="col-lg-3 col-md-6 text-center">
          <div class="mt-5">
            <i class="fas fa-4x fa-gem text-primary mb-4"></i>
            <h3 class="h4 mb-2">노력의 빛을 볼 수 있다</h3>
            <p class="text-muted mb-0">농촌 일은 하면서 노력의 빛을 볼 수 있다.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="mt-5">
            <i class="fas fa-4x fa-laptop-code text-primary mb-4"></i>
            <h3 class="h4 mb-2">농촌의 대해 새로운 정보를 얻을 수 있다</h3>
            <p class="text-muted mb-0">농민들의 일을 도와주면서 농촌의 대해 알 수 있다.  </p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="mt-5">
            <i class="fas fa-4x fa-globe text-primary mb-4"></i>
            <h3 class="h4 mb-2">인맥을 넓힐 수 있다</h3>
            <p class="text-muted mb-0">여러 사람들을 만나서 친해진다.</p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 text-center">
          <div class="mt-5">
            <i class="fas fa-4x fa-heart text-primary mb-4"></i>
            <h3 class="h4 mb-2">선후배 관계가 독득해진다</h3>
            <p class="text-muted mb-0">10일 동안 같이 생활하면서 선후배 관계가 독득해진다.</p>
          </div>
        </div>
      </div>
      <a class="btn btn-light btn-xl js-scroll-trigger" href="{% url 'newblog' %}#portfolio1" style="text-align: center; margin-top: 20px;">농활 게시판 글쓰기</a>
    </div>
  </section>

  <!-- Portfolio Section -->
  <section id="portfolio">
    <div class="container-fluid p-0">
      <div class="row no-gutters">
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/n1.jpg' %}">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/n1.jpg' %}" alt="">
            <div class="portfolio-box-caption">
              <div class="project-category text-white-50">
                논밭
              </div>
              <div class="project-name">
                늪이다
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/n2.jpg' %}">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/n2.jpg' %}" alt="">
            <div class="portfolio-box-caption">
              <div class="project-category text-white-50">
                경운기
              </div>
              <div class="project-name">
                덜덜덜
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/n3.jpg' %}">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/n3.jpg' %}" alt="">
            <div class="portfolio-box-caption">
              <div class="project-category text-white-50">
                복숭아 밭
              </div>
              <div class="project-name">
                반짝반짝
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/n4.jpg' %}">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/n4.jpg' %}" alt="">
            <div class="portfolio-box-caption">
              <div class="project-category text-white-50">
                계곡
              </div>
              <div class="project-name">
                시원시원
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/n5.jpg' %}">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/n5.jpg' %}" alt="">
            <div class="portfolio-box-caption">
              <div class="project-category text-white-50">
                시골 갬성
              </div>
              <div class="project-name">
                조용하구만
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/n6.jpg' %}">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/n6.jpg' %}" alt="">
            <div class="portfolio-box-caption p-3">
              <div class="project-category text-white-50">
                시골 개
              </div>
              <div class="project-name">
                태풍이~~
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </section>

  <!-- Call to Action Section -->
  <section class="page-section bg-dark text-white" id="portfolio1">
    <div class="container text-center">
      <h2 class="mb-4" style="font-size: 40px;">농촌 봉사 활동 게시판 글쓰기</h2>
      {% block content %}
      {% endblock %}
      <!-- <a class="btn btn-light btn-xl" href="{% url 'newblog' %}#portfolio">글쓰기!!</a> -->
    </div>
  </section>

  <!-- Contact Section -->
  <section class="page-section" id="contact">
    <div class="container" style="padding: 10px 50px">
      <p style="font-size: 50px; color: firebrick; text-align: center;">농촌 봉사 활동 게시판</p>
      {% block contnent1 %}
      {% endblock %}
    </div>
  </section>

  <!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
      <div class="small text-center text-muted">Copyright &copy; 2019 - Start Bootstrap</div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/creative.min.js' %}"></script>

</body>

</html>

velvet/templates/new.html
{% extends 'layout.html' %}
{% block content %}
    <form method='POST' enctype="multipart/form-data">
        {% csrf_token %}
    <div class="new_table" style="text-align: center;">
        <table style="width: 500px; margin-left: 290px;">
            {{form.as_table}}
        </table>
    </div>
        <input class="btn btn-light btn-xl" onClick="location.href='#contact'" type="submit" value="제출하기">
    </form>

{% endblock %}

velvet/templates/search.html
{% extends 'layout.html' %}

{% block header %}
<!-- Page Header -->
<header class="masthead" style="background-image: url('/static/app/img/home-bg.jpg')">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
              <h1>{{ hashtag }}가 있는 게시글 목록</h1>
              <span class="subheading">해시태그 검색결과 페이지 입니다.</span>
             </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block content %}
<!-- Main Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
    {% for blog in hashtag.blog_set.all %}
      <div class="post-preview">
        <a href="{% url 'hashtag' %}">
          <h2 class="post-title">
            {{ blog.title }}
          </h2>
          <h3 class="post-subtitle">
            {{ blog.summary }}
          </h3>
        </a>
        <p class="post-meta">
          {{ blog.pub_date }}</p>
      </div>
      <hr>
      {% endfor %}
      <!-- Pager -->
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}